version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '10000:80'

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=Ilia_24998
      - MYSQL_DATABASE=server
      - MYSQL_USER=ilya
      - MYSQL_PASSWORD=secret
    ports:
      - "3308:3306"